<BR><BR><div class="titulo_conteudo">Ciências Exatas - PIBIC_EM</div><BR><div class="titulo_area">Ciências Exatas e da Terra / Exact Sciences and Engineering</div><font class="art1">DIR01jr             </font><div class="trabalho"><a href="trabalho.php?dd0=12139&dd90=1bb84661c8&dd10=view.html" class="art2"><B>The legal regime of production of clean and renewable energy as a means of promoting sustainable development</B></A><BR><font class="art3"><I>GASPARIN, Eduardo Cezar; ALUNO
SANCHES, Luiz Antonio Ugeda; COLABORADOR
BLANCHET, Luiz Alberto;ORIENTADOR</I></font><BR>&nbsp;</div><font class="art1">BIOG01jr            </font><div class="trabalho"><a href="trabalho.php?dd0=12136&dd90=0da44cdf27&dd10=view.html" class="art2"><B>Reproductive strategy of Loxosceles gaucho: sperm reserves in the bulbs copulatory of males</B></A><BR><font class="art3"><I>MACIOSZEK, Daiane; AMARAL, Vanessa de Oliveira; FISCHER, Marta 
Luciane</I></font><BR>&nbsp;</div><BR><BR><div class="titulo_conteudo">Ciências Agrárias - PIBIC_EM</div><BR><div class="titulo_area">Medicina Veterinária / Veterinary medicine</div><font class="art1">MEDVET03jr          </font><div class="trabalho"><a href="trabalho.php?dd0=12138&dd90=0e30a1c5b2&dd10=view.html" class="art2"><B>Water quality in the trasport of pacu (Piaractus mesopotamicus) with different concentrations of salt (NaCl)</B></A><BR><font class="art3"><I>PISSAIA, Marcus Vinícius; BALDAN, Ana Paula</I></font><BR>&nbsp;</div><font class="art1">MEDVET01jr          </font><div class="trabalho"><a href="trabalho.php?dd0=12134&dd90=d57087487e&dd10=view.html" class="art2"><B>Preliminary results of osteochondrosis incidence in thorough bred weanlings in the region of Curitiba, Brazil</B></A><BR><font class="art3"><I>CARRÃO, Kamilla C.; DAVID, Hilana; BASTOS, Luis Fernando 
Coelho; SILVEIRA, Andressa; DUBIELA, Amarildo; MICHELOTTO Jr., 
Pedro Vicente</I></font><BR>&nbsp;</div><font class="art1">MEDVET02jr          </font><div class="trabalho"><a href="trabalho.php?dd0=12135&dd90=5238f9e188&dd10=view.html" class="art2"><B>Thermographic Evaluation of the Thoracolumbar Region of a Police Horse after Using Different Working Saddles</B></A><BR><font class="art3"><I>FRANÇA, Jamille Melka da Rocha; TINCANI, Flávio; KOZEMJAKIN, 
Denise; VILLA Sara; TAVARES, Fernanda; MICHELOTTO Jr., Pedro 
Vicente</I></font><BR>&nbsp;</div><BR><BR><div class="titulo_conteudo">Ciências Sociais Aplicadas - PIBIC_EM</div><BR><div class="titulo_area">Arquitetura e Urbanismo / Architecture and Urbanism</div><font class="art1">ARQUR01jr           </font><div class="trabalho"><a href="trabalho.php?dd0=12176&dd90=ad6c9be0d3&dd10=view.html" class="art2"><B>Research on sustainable housing</B></A><BR><font class="art3"><I>ARCE, Maria Pulido; SCHUSSEL, Zulma das Graças Lucena.</I></font><BR>&nbsp;</div><BR><BR><div class="titulo_conteudo">Ciências Humanas - PIBIC_EM</div><BR><div class="titulo_area">Educação / Education</div><font class="art1">EDU01Jr             </font><div class="trabalho"><a href="trabalho.php?dd0=12175&dd90=bb45d0bc77&dd10=view.html" class="art2"><B>Using the Eureka environment by look of students of courses bachelor of PUCPR</B></A><BR><font class="art3"><I>NASCIMENTO, Cibele Zolnier Souza do;CASTELEINS, Vera Lúcia.</I></font><BR>&nbsp;</div><font class="art1">EDU02jr             </font><div class="trabalho"><a href="trabalho.php?dd0=12140&dd90=eb6be266ad&dd10=view.html" class="art2"><B>Creation of a technology tool to develop a learning culture at the university</B></A><BR><font class="art3"><I>MORAIS, Vinicios de; 
BORATO, Ana Debora Popovicz; ALVES, Guilherme; DALLEGRAVE, 
Juslaine Lucília Mickosz de; VOSGERAU, Dilmeire Sant’Anna 
Ramos</I></font><BR>&nbsp;</div><font class="art1">EDU03jr             </font><div class="trabalho"><a href="trabalho.php?dd0=12141&dd90=e02697f754&dd10=view.html" class="art2"><B>Internet helping developing a culture of learning at the university</B></A><BR><font class="art3"><I>BORATO, Ana Débora Popovicz; DALLEGRAVE, Juslaine Lucília 
Mickosz de; BIALLI, Miriam; SCHELEDER, Janete; VOSGERAU, 
Dilmeire Sant’Anna Ramos</I></font><BR>&nbsp;</div><BR><div class="titulo_area">Letras / Languages and Literature</div><font class="art1">LETR01jr            </font><div class="trabalho"><a href="trabalho.php?dd0=12137&dd90=6c3b1f79c0&dd10=view.html" class="art2"><B>The role of the native Brazilian interpreter in the construction of cultural identities</B></A><BR><font class="art3"><I>SANTOS, Kleys Jesuvina dos; FONSECA NETO, Syllas Moreira da; 
THIÉL, Janice Cristine.</I></font><BR>&nbsp;</div><BR><font class="art0">Total de 10 trabalhos</font>