<BR><BR><div class="titulo_conteudo">Ciências Exatas - PIBIC_EM</div><BR><div class="titulo_area">Ciências Exatas e da Terra / Exact Sciences and Engineering</div><font class="art1">DIR01jr             </font><div class="trabalho"><a href="trabalho.php?dd0=12139&dd90=1bb84661c8&dd10=view.html" class="art2"><B>O regime jurídico da produção de energia limpa e renovável como instrumento promotor do desenvolvimento sustentável</B></A><BR><font class="art3"><I>GASPARIN, Eduardo Cezar; ALUNO
SANCHES, Luiz Antonio Ugeda; COLABORADOR
BLANCHET, Luiz Alberto;ORIENTADOR</I></font><BR>&nbsp;</div><font class="art1">BIOG01jr            </font><div class="trabalho"><a href="trabalho.php?dd0=12136&dd90=0da44cdf27&dd10=view.html" class="art2"><B>Estratégia reprodutiva de Loxosceles gaucho: reserva espermática nos bulbos copulatórios dos machos</B></A><BR><font class="art3"><I>MACIOSZEK, Daiane; AMARAL, Vanessa de Oliveira; FISCHER, Marta 
Luciane</I></font><BR>&nbsp;</div><BR><BR><div class="titulo_conteudo">Ciências Agrárias - PIBIC_EM</div><BR><div class="titulo_area">Medicina Veterinária / Veterinary medicine</div><font class="art1">MEDVET03jr          </font><div class="trabalho"><a href="trabalho.php?dd0=12138&dd90=0e30a1c5b2&dd10=view.html" class="art2"><B>Qualidade da água no trasporte de pacus (<I>Piaractus mesopotamicus</I>) com diferentes concentrações de sal (NACL)</B></A><BR><font class="art3"><I>PISSAIA, Marcus Vinícius; BALDAN, Ana Paula</I></font><BR>&nbsp;</div><font class="art1">MEDVET01jr          </font><div class="trabalho"><a href="trabalho.php?dd0=12134&dd90=d57087487e&dd10=view.html" class="art2"><B>Resultados preliminares sobre a incidência de osteocondrose em potros puro sangue inglês dos 4 aos 6 meses de idade, na região de Curitiba, PR</B></A><BR><font class="art3"><I>CARRÃO, Kamilla C.; DAVID, Hilana; BASTOS, Luis Fernando 
Coelho; SILVEIRA, Andressa; DUBIELA, Amarildo; MICHELOTTO Jr., 
Pedro Vicente</I></font><BR>&nbsp;</div><font class="art1">MEDVET02jr          </font><div class="trabalho"><a href="trabalho.php?dd0=12135&dd90=5238f9e188&dd10=view.html" class="art2"><B>Avaliação termográfica da região toracolombar de cavalo de patrulha após o uso de diferentes selas de trabalho</B></A><BR><font class="art3"><I>FRANÇA, Jamille Melka da Rocha; TINCANI, Flávio; KOZEMJAKIN, 
Denise; VILLA Sara; TAVARES, Fernanda; MICHELOTTO Jr., Pedro 
Vicente</I></font><BR>&nbsp;</div><BR><BR><div class="titulo_conteudo">Ciências Sociais Aplicadas - PIBIC_EM</div><BR><div class="titulo_area">Arquitetura e Urbanismo / Architecture and Urbanism</div><font class="art1">ARQUR01jr           </font><div class="trabalho"><a href="trabalho.php?dd0=12176&dd90=ad6c9be0d3&dd10=view.html" class="art2"><B>Pesquisa sobre moradia sustentável</B></A><BR><font class="art3"><I>ARCE, Maria Pulido; SCHUSSEL, Zulma das Graças Lucena.</I></font><BR>&nbsp;</div><BR><BR><div class="titulo_conteudo">Ciências Humanas - PIBIC_EM</div><BR><div class="titulo_area">Educação / Education</div><font class="art1">EDU01Jr             </font><div class="trabalho"><a href="trabalho.php?dd0=12175&dd90=bb45d0bc77&dd10=view.html" class="art2"><B>A utilização do ambiente Eureka pelo olhar dos alunos dos cursos de licenciatura da PUCPR</B></A><BR><font class="art3"><I>NASCIMENTO, Cibele Zolnier Souza do;CASTELEINS, Vera Lúcia.</I></font><BR>&nbsp;</div><font class="art1">EDU02jr             </font><div class="trabalho"><a href="trabalho.php?dd0=12140&dd90=eb6be266ad&dd10=view.html" class="art2"><B>Criação de ferramenta tecnológica para desenvolver uma cultura de aprendizagem na universidade</B></A><BR><font class="art3"><I>MORAIS, Vinicios de; 
BORATO, Ana Debora Popovicz; ALVES, Guilherme; DALLEGRAVE, 
Juslaine Lucília Mickosz de; VOSGERAU, Dilmeire Sant’Anna 
Ramos</I></font><BR>&nbsp;</div><font class="art1">EDU03jr             </font><div class="trabalho"><a href="trabalho.php?dd0=12141&dd90=e02697f754&dd10=view.html" class="art2"><B>A internet auxiliando o desenvolvimento de uma cultura de aprendizagem na universidade</B></A><BR><font class="art3"><I>BORATO, Ana Débora Popovicz; DALLEGRAVE, Juslaine Lucília 
Mickosz de; BIALLI, Miriam; SCHELEDER, Janete; VOSGERAU, 
Dilmeire Sant’Anna Ramos</I></font><BR>&nbsp;</div><BR><div class="titulo_area">Letras / Languages and Literature</div><font class="art1">LETR01jr            </font><div class="trabalho"><a href="trabalho.php?dd0=12137&dd90=6c3b1f79c0&dd10=view.html" class="art2"><B>O papel do intérprete nativo na construção da identidade cultural</B></A><BR><font class="art3"><I>SANTOS, Kleys Jesuvina dos; FONSECA NETO, Syllas Moreira da; 
THIÉL, Janice Cristine.</I></font><BR>&nbsp;</div><BR><font class="art0">Total de 10 trabalhos</font>