<div id="trabalho">
	<table width="100%" border=0>
		<tr valign="top">
			<td colspan=2>SILVA, M. M. D.; TEIXEIRA, E. C. B. Os impactos do esocial no meio empresarial contábil. In: SEMIC, Seminário de Iniciação Científica, 23, 2015, Curitiba-PR. Anais do 23º Seminário de Iniciação Científica. Curitiba: PUCPR, 2015. p. ADM25.</td>
			<td width="100" align="right" rowspan=2>
				Pôster				<br>
				<img src="<?php echo base_url('img/semic/icone-poster-grad.png');?>" title="Pôster">
			</td>
		</tr>
		<tr>
			<td colspan=2 class="lt3"><font class="lt6">ADM25</font>
				<br><b>Administração</b></td>
		</tr>
		<tr>
			<td align="center"><font class="lt5"><b>Os impactos do esocial no meio empresarial contábil</b></font>
			<BR>
			<font class="lt4"><i>The impact of esocial in the accounting business market</i></font>
			<BR>
			</td>
		</tr>
	</table>
	<br>
	<div style="text-align:right;">
		SILVA, Matheus Moreira Dias da<sup>1</sup>; TEIXEIRA, Elenice Cacia Bittencourt<sup>2</sup>		<BR>
		PIBIC		- Opção para Iniciação Científica Voluntária		<BR>
		<I>--</I>
	</div>
	<BR>
	<table width="100%">
		<tr valign="top">
			<td width="44%"> Resumo
			<div style="text-align:justify;">
				<P>
					<B>Introdução</B>: O desenvolvimento da ciência contábil está atrelado ao aperfeiçoamento das relações econômicas: sendo estas mais complexas, requerem que a contabilidade suporte tamanha demanda. Dessa forma, a prática contábil passa gradativamente a utilizar-se de tecnologia da informação para se adequar ao cenário em que se insere. Não só para o contexto empresarial, os produtos gerados pela contabilidade são usados também em caráter fiscalizatório pela Administração Pública. Como reflexo desse modelo informatizado de prestação de contas, em 2007 o Governo implementa o Sistema Público de Escrituração Digital (SPED) e em 2010 iniciaram os trabalhos da chamada Escrituração Fiscal Digital Social, para que em 2012 fosse instaurado o que hoje é conhecido por eSocial. O e-Social é uma plataforma que vai unificar o envio de informações trabalhistas e previdenciárias ao fisco por empregadores em geral.					<B>Objetivo</B>: Como objetivo, o presente trabalho vislumbra evidenciar como as empresas de contabilidade de Londrina estão se preparando para atender ao eSocial - estabelecendo uma conjuntura, além de identificar a receptividade do programa quanto à medidas internas cabíveis.					<B>Metodologia</B>: Para atender a estes critérios, como pesquisa de caráter original, foi aplicado um questionário misto no período de setembro de 2014 a junho de 2015, com característica majoritariamente de mensuração, que pretende estabelecer um cenário abrangente em uma amostra não-probabilística por conveniência.					<B>Resultados</B>: A situação se mostra equilibrada – 28,57% da amostra se define parcialmente inapta ao programa, quanto 26,19% se diz apta. Os escritórios atribuem ao sistema de controle interno a medida mais crucial para adequação ao eSocial.					<B>Conclusões</B>: A pesquisa mostra que a adequação ao eSocial depende de um sistema gerencial que comporte o programa. Ou seja, a tecnologia pela tecnologia.				</P>
			</div><B>Palavras-chave</B>: ESocial. Empresas de Contabilidade. SPED			<BR>
			<BR>
			</td><td width="2%">&nbsp;</td><td width="44%"> Abstract
			<div style="text-align:justify;">
				<P>
					<B>Introduction</B>: The development of accounting science is linked to the improvement of economic relations: which were more complex, require accounting support such demand. Thus, the accounting practice gradually begins to use technology to suit the scenario in which it operates. Not only for the business environment, the products generated by accounting are used also in fiscalization by the Government. Reflecting this accountability computerized model, in 2007 the Government implements the Public Digital Bookkeeping System (SPED) and in 2010 began the work of the Fiscal Social Digital Bookkeeping, so that in 2012 was deployed what is now known for eSocial. The e-Social is a platform that will unify the sending of labor and social security information to the tax authorities by employers in general.					<B>Objectives</B>: As a goal, this work intends to evidence as Londrina accounting firms are preparing to meet the eSocial - establishing a situation and identify the reactivity of the program as the appropriate internal measures.					<B>Methods</B>: To meet these criteria, such as original research study, it applied a mixed questionnaire from September 2014 to June 2015, mainly with measurement feature, which aims to establish a comprehensive scenario in a non-probabilistic convenience sample. The situation shows balanced - 28.57% of the sample is defined partially unfit for the program, as 26.19% is said apt.					<B>Results</B>: Offices attribute to the internal control system the most crucial measure to fit the eSocial.					<B>Conclusion</B>: Research shows that matching the eSocial depends on a management system carrying the program. So, technology by technology.				</P>
			</div><B>Keywords</B>: ESocial. Accounting Companies. SPED</td>
		</tr>
	</table>
	<BR>
	<BR>
	<sup>1</sup> Estudante. PUCPR<br><sup>2</sup> Orientador. PUCPR	<BR>
	<BR>
	<BR>
	<BR>
</div>
<BR>
<BR>
<BR>
</div> 