<div id="trabalho">
	<table width="100%" border=0>
		<tr valign="top">
			<td colspan=2>KLENK, G.; RUSSO NETO, L. Cravabilidade de estacas: análise da rigidez do coxim. In: SEMIC, Seminário de Iniciação Científica, 23, 2015, Curitiba-PR. Anais do 23º Seminário de Iniciação Científica. Curitiba: PUCPR, 2015. p. ECV5T.</td>
			<td width="100" align="right" rowspan=2>
				Pôster				<br>
				<img src="<?php echo base_url('img/semic/icone-poster-grad.png');?>" title="Pôster">
			</td>
		</tr>
		<tr>
			<td colspan=2 class="lt3"><font class="lt6">ECV5T</font>
				<br><b>Engenharia Civil</b></td>
		</tr>
		<tr>
			<td align="center"><font class="lt5"><b>Cravabilidade de estacas: análise da rigidez do coxim</b></font>
			<BR>
			<font class="lt4"><i>Drivability of piles: analysis of the cushion rigidity</i></font>
			<BR>
			</td>
		</tr>
	</table>
	<br>
	<div style="text-align:right;">
		KLENK, Gislaine<sup>1</sup>; RUSSO NETO, Luiz<sup>2</sup>		<BR>
		PIBITI		- Bolsa Agência PUC		<BR>
		<I>--</I>
	</div>
	<BR>
	<table width="100%">
		<tr valign="top">
			<td width="44%"> Resumo
			<div style="text-align:justify;">
				<P>
					<B>Introdução</B>: Na engenharia, a execução de estacas faz-se necessária quando o solo próximo à superfície não resiste as cargas advindas da superestrutura. O uso de estacas pré-moldadas, inseridas no maciço do solo por percussão com martelo e bate-estacas de queda livre, é um dos métodos mais utilizados no Brasil. Neste estudo, propõe-se dar continuidade à linha de pesquisa, que visa a otimização do sistema de cravação, através do menor número de golpes sem promover a quebra da estaca. O processo de cravação de estacas pode ser modelado pela teoria da propagação da onda. Com a adaptação deste método para ferramentas computacionais, como o GRLWEAP (WEAP - Weave Equation Analysis of Pile Driving), é possível simular e selecionar o tipo de sistema de cravação adequado para uma determinada situação.					<B>Objetivo</B>: Este projeto tem por objetivo analisar a influência do módulo de elasticidade do sistema de amortecimento, coxim, na cravação de estacas pré-moldadas de concreto.					<B>Metodologia</B>: Foi efetuada a análise dos relatórios gerados por simulações no programa GRLWEAP. Nele, foi realizada a variação do módulo de elasticidade do coxim de espessura 200 mm (entre as madeiras Madeirit e Jatobá), das alturas de queda e dos pesos do martelo (10, 20 e 30 kN). A estaca terá seção transversal 30 por 30 cm, comprimento de 10 m, capacidade de carga de 1.080 kN sendo esta distribuída 50% de resistência de ponta e lateral.					<B>Resultados</B>: Dos resultados obtidos, observou-se que os valores de tensão de compressão máxima, nega e deslocamento máximo, aumentam com a altura de queda e o peso do martelo, sendo os maiores valores para o coxim de Jatobá. Para uma mesma energia dispendida na cravação, os coxins de Jatobá obtiveram os maiores valores de força e velocidade, com uma menor amplitude em relação ao coxim de Madeirit.					<B>Conclusões</B>: Observou-se que, com a mesma energia, martelos mais pesados com alturas de queda menores são mais eficientes, pois geram um menor número de golpes. O coxim de Jatobá conduz a um menor espectro de energia, pois a estaca quebra com mais facilidade e para alturas de queda inferiores ao coxim de Madeirit.				</P>
			</div><B>Palavras-chave</B>: Cravabilidade. Estacas pré-moldadas. Sistema de amortecimento.			<BR>
			<BR>
			</td><td width="2%">&nbsp;</td><td width="44%"> Abstract
			<div style="text-align:justify;">
				<P>
					<B>Introduction</B>: In engineering, the implementation of piles is required when the soil close to the surface does not resist the loads applied by superstructure. The use of precast piles in soil by percussion with freefall hammer and pile driving is one of the most widely used methods in Brazil. In this study, we propose to continue a line of research that aims to optimize the driving system through fewer total strokes without promoting the pile break. The installation process can be modeled by the theory of wave propagation. By adapting this method for computational tools such as GRLWEAP (WEAP - Weave Equation Analysis of Pile Driving), you can simulate and select the type of system suitable for a given situation.					<B>Objectives</B>: This project aims to analyze the influence of the elastic modulus of the damping system, cushion, for precast concrete piles.					<B>Methods</B>: The analysis was made of the reports generated by the simulation program GRLWEAP where there was a variation of 200 mm thick cushion modulus (Plywood between the timber and Jatoba), the drop heights and weights of the hammer (10, 20 and 30 kN). The pile has cross section 30 by 30 cm, length 10 m, 1080 kN load capacity and this distributed 50% tip resistance and side.					<B>Results</B>: From the results, it was observed that the maximum compressive stress values, denies and maximum displacement, increase with the drop height and the hammer weight, with higher values for the cushion of Jatoba. For the same energy expended in spiking, cushions Jatoba had the highest values of strength and speed, with a smaller amplitude compared to cushion Plywood.It was observed that with the same energy, heavier hammers with lower drop heights are more efficient, because they generate fewer strokes. The Jatoba cushion leads to a lower energy spectrum, as the cutting breaks more easily and at lower drop heights cushion Plywood.					<B>Conclusion</B>: It was observed that with the same energy, heavier hammers with lower drop heights are more efficient, because they generate fewer strokes. The Jatoba cushion leads to a lower energy spectrum, as the cutting breaks more easily and at lower drop heights cushion Plywood.				</P>
			</div><B>Keywords</B>: Drivability. Precast piles. Dampening System.</td>
		</tr>
	</table>
	<BR>
	<BR>
	<sup>1</sup> Estudante. PUCPR<br><sup>2</sup> Orientador. PUCPR	<BR>
	<BR>
	<BR>
	<BR>
</div>
<BR>
<BR>
<BR>
</div> 