<div id="trabalho">
	<table width="100%" border=0>
		<tr valign="top">
			<td colspan=2>RIBAS, P. S.; CUNHA, E. B.; AITA, C. A. M. Análise [e]lt;i[e]rt;[e]lt;i[e]rt;in vitro[e]lt;/i[e]rt;[e]lt;/i[e]rt; do extrato de campomanesia xanthocarpa na ativação celular em linhagens monocíticas. In: SEMIC, Seminário de Iniciação Científica, 23, 2015, Curitiba-PR. Anais do 23º Seminário de Iniciação Científica. Curitiba: PUCPR, 2015. p. MED69.</td>
			<td width="100" align="right" rowspan=2>
				Oral/Pôster				<br>
				<img src="<?php echo base_url('img/semic/icone-oral-post-grad.png');?>" title="Oral/Pôster">
			</td>
		</tr>
		<tr>
			<td colspan=2 class="lt3"><font class="lt6">MED69</font>
				<br><b>Medicina</b></td>
		</tr>
		<tr>
			<td align="center"><font class="lt5"><b>Análise [e]lt;i[e]rt;[e]lt;i[e]rt;in vitro[e]lt;/i[e]rt;[e]lt;/i[e]rt; do extrato de campomanesia xanthocarpa na ativação celular em linhagens monocíticas</b></font>
			<BR>
			<font class="lt4"><i>[e]lt;/i[e]rt;[e]lt;i[e]rt;in vitro[e]lt;/i[e]rt;[e]lt;i[e]rt; analysis of campomanesia xanthocarpa extract in the activation of the THP-1 monocytic cell line</i></font>
			<BR>
			</td>
		</tr>
	</table>
	<br>
	<div style="text-align:right;">
		RIBAS, Patricia Santos<sup>1</sup>; CUNHA, Eduardo Brunetti<sup>2</sup>; AITA, Carlos Alberto Mayora<sup>3</sup>		<BR>
		PIBIC		- Bolsa CNPq-PIBIC		<BR>
		<I>--</I>
	</div>
	<BR>
	<table width="100%">
		<tr valign="top">
			<td width="44%"> Resumo
			<div style="text-align:justify;">
				<P>
					<B>Introdução</B>: A aterosclerose é uma doença inflamatória crônica multifatorial, intimamente ligada aos monócitos e macrófagos que desempenham papel importante na formação das placas ateroscleróticas. Estimulados por citocinas inflamatórias e pelo aumento das moléculas de adesão celular como a ICAM-1 (CD54) os monócitos migram para o espaço subendotelial e se diferenciam em macrófagos. Retidos no espaço subendotelial e submetidos a um ambiente de stress oxidativo, os macrófagos passam a sintetizar citocinas que perpetuam o processo inflamatório. Atuando como um co-receptor, o CD14 se liga a partículas de LDL modificadas que também potencializa a secreção de citocinas. O endotélio danificado perde a sua propriedade antiagregante plaquetária, anticoagulante e fibrinolítica, adquirindo atividade pró-coagulante. Por essa razão é de suma importância o controle dos níveis séricos de colesterol. Na busca por novas terapêuticas hipolipemiantes, um estudo recente comprovou que o extrato de Campomanesia xantocharpa (“Guavirova”) é capaz de diminuir o colesterol e o stress oxidativo do plasma de pacientes hipercolesterolêmicos. Contudo, pouco foi avaliado até o momento sobre possíveis efeitos diretos desta planta sobre as células envolvidas no processo aterosclerótico.					<B>Objetivo</B>: Determinar se o extrato de C. xantocharpa altera a viabilidade celular dos monócitos humanos (THP-1) e se o mesmo é capaz de modular [e]lt;i[e]rt;in vitro[e]lt;/i[e]rt; a expressão do CD14 e CD54, os quais fazem parte do processo inflamatório vinculado a aterogênese.					<B>Metodologia</B>: A viabilidade celular foi verificada pelos métodos de contagem celular e MTT. A avaliação da expressão de CD14 foi realizada por citometria de fluxo. Para análise dos resultados utilizou-se o teste t de student e Wilcoxon.					<B>Resultados</B>: A viabilidade celular de uma linhagem de monócitos humanos (THP-1) não foi significativamente comprometida nas seguintes concentrações do extrato de guavirova: 25, 50, 100 µg/ml. Contudo, em altas concentrações (500 µg/ml) a viabilidade foi prejudicada. As células THP-1 na presença do extrato de C. xantocharpa reduziram a expressão da molécula CD14 (média 46,381%), quando comparada ao grupo controle (média 56,515%), (p= 0,02771).					<B>Conclusões</B>: O extrato de C. xantocharpa não modificou significativamente a viabilidade celular, exceto quando em alta concentração (500 µg/ml). Os monócitos humanos (THP-1), na presença do extrato da guavirova diminuíram a expressão do CD14.				</P>
			</div><B>Palavras-chave</B>: Aterosclerose. Monócitos. Antígenos CD14			<BR>
			<BR>
			</td><td width="2%">&nbsp;</td><td width="44%"> Abstract
			<div style="text-align:justify;">
				<P>
					<B>Introduction</B>: Atherosclerosis is a chronic multifactorial inflammatory disease closely related to monocytes and macrophages, that play an important role in the formation of atherosclerotic plaques. Being stimulated by inflammatory cytokines and by an increase in cell adhesion molecules such as ICAM-1 (CD54) the monocytes migrate into the subendothelial space and differentiate into macrophages. Retained in the subendothelial space and subjected to an environment of oxidative stress generated by reactive oxygen species, macrophages begin to synthesize cytokines that perpetuate the inflammatory process. Acting as a co-receptor, CD14 binds to modified LDL particles which also enhances the secretion of inflammatory cytokines. This damaged endothelium loses its antiplatelet, anticoagulant and fibrinolytic property, acquiring procoagulant activity. Therefore it is extremely important to control cholesterol levels. In the search for new lipid-lowering treatments, a recent study based on the popular belief, showed that the extract of Campomanesia xantocharpa ("Guavirova") is able to lower cholesterol, especially LDL, and oxidative stress in plasma of patients with hypercholesterolemia. However, few studies have been reported so far concerning possible direct effects of this plant on the cells involved in the atherosclerotic process.					<B>Objectives</B>: To evaluate if the extract of Campomanesia xantocharpa alters cell viability of human monocytes (THP-1) and if it is able to modulate [e]lt;i[e]rt;in vitro[e]lt;/i[e]rt; the expression of CD14 and CD54, which are part of the inflammatory process linked to atherogenesis.					<B>Methods</B>: Cell viability was measured by the MTT method. The expression of CD14 receptor was performed by flow cytometry. For data analysis we used the Student t test and Wilcoxon.					<B>Results</B>: Cell viability of human monocytes (THP-1) was not significantly compromised under the following guavirova extract concentrations: 25, 50, 100 µg/ml. However at high concentrations (500 µg/ml) the viability was impaired. THP-1 cells in the presence of the extract of Campomanesia xantocharpa reduced the expression of CD14 molecule (mean 46.381%) compared to the control group (mean 56.515%), (p = 0.02771).					<B>Conclusion</B>: The extract of C. xantocharpa did not significantly alter cell viability, except when in high concentrations (500 µg/ml). Human monocytes (THP-1), in the presence of the guavirova extract decreased the expression of CD14.				</P>
			</div><B>Keywords</B>: Atherosclerosis. Monocytes. CD14 antigens</td>
		</tr>
	</table>
	<BR>
	<BR>
	<sup>1</sup> Estudante. PUCPR<br><sup>3</sup> Orientador. PUCPR	<BR>
	<BR>
	<BR>
	<BR>
</div>
<BR>
<BR>
<BR>
</div> 