<div id="trabalho">
	<table width="100%" border=0>
		<tr valign="top">
			<td colspan=2>ORNELLAS, C. A. D.; RUSSO NETO, L. Ensaio de integridade em estacas - pit. In: SEMIC, Seminário de Iniciação Científica, 23, 2015, Curitiba-PR. Anais do 23º Seminário de Iniciação Científica. Curitiba: PUCPR, 2015. p. ECV2T.</td>
			<td width="100" align="right" rowspan=2>
				Pôster				<br>
				<img src="<?php echo base_url('img/semic/icone-poster-grad.png');?>" title="Pôster">
			</td>
		</tr>
		<tr>
			<td colspan=2 class="lt3"><font class="lt6">ECV2T</font>
				<br><b>Engenharia Civil</b></td>
		</tr>
		<tr>
			<td align="center"><font class="lt5"><b>Ensaio de integridade em estacas - pit</b></font>
			<BR>
			<font class="lt4"><i>Pile integrity test - pit</i></font>
			<BR>
			</td>
		</tr>
	</table>
	<br>
	<div style="text-align:right;">
		ORNELLAS, Carolina Araujo D<sup>1</sup>; RUSSO NETO, Luiz<sup>2</sup>		<BR>
		PIBITI		- Opção para Iniciação Tecnológica Voluntária		<BR>
		<I>--</I>
	</div>
	<BR>
	<table width="100%">
		<tr valign="top">
			<td width="44%"> Resumo
			<div style="text-align:justify;">
				<P>
					<B>Introdução</B>: Diante da impossibilidade de se verificar a integridade de todas as estacas de uma obra com o uso do PDA, foi desenvolvido um ensaio não destrutivo exclusivo para esta finalidade, denominado PIT (Pile Integrity Tester), com base na interpretação da onda de tensão gerada por golpes no topo da estaca.					<B>Objetivo</B>: Neste trabalho, é apresentado o ensaio PIT (obtidos em três estacas) com diferentes tipos de dosagem.					<B>Metodologia</B>: Os resultados coletados foram transferidos para um programa de computador específico, denominado PIT-W (PDI, 2003), onde tornou-se possível interpretar e determinar se as variações são aceitáveis ou de grande preocupação para a integridade.					<B>Resultados</B>: Os registros de instalação, o volume de concreto, comprimento da estaca e outras observações também foram levados em conta durante toda a interpretação. As estacas com utilização de agregado mais graúdo conduziram a maiores velocidades de ondas.					<B>Conclusões</B>: Foi possível quantificar a variação da velocidade de propagação da onda com o tempo de cura de cada traço.				</P>
			</div><B>Palavras-chave</B>: Estacas. Ensaios não destrutivos. Ensaio de integridade de estacas.			<BR>
			<BR>
			</td><td width="2%">&nbsp;</td><td width="44%"> Abstract
			<div style="text-align:justify;">
				<P>
					<B>Introduction</B>: Given the inability to verify the integrity of every stakes used in a work with PDA, it was developed a non-destructive test unique for this purpose: PIT (Pile Integrity Tester, based on the interpretation of the voltage waveform generated by scams on the top of the pile.					<B>Objectives</B>: In this work the assay was presented PIT (obtained with three piles) in different dosage.					<B>Methods</B>: The results collected were transferred to a specific computer program called PIT-W (PDI, 2003) where it became possible to interpret and determine whether the changes are acceptable or concern for the integrity.					<B>Results</B>: The installation logs, concrete volume, cutting length and other observations were also taken into account during the whole observation. Pile tested with coarser agregates show higher values of wave  speed.					<B>Conclusion</B>: The results indicate that the wave speed increase as the time goes on and are acording to the equipment manual. Values between 2.500 to 3.400 m/s are registered.				</P>
			</div><B>Keywords</B>: Piles. Non destructive techniques. Pile Integrity Test.</td>
		</tr>
	</table>
	<BR>
	<BR>
	<sup>1</sup> Estudante. PUCPR<br><sup>2</sup> Orientador. PUCPR	<BR>
	<BR>
	<BR>
	<BR>
</div>
<BR>
<BR>
<BR>
</div> 