<div id="trabalho">
	<table width="100%" border=0>
		<tr valign="top">
			<td colspan=2>ANDRADE, R.; CHUEIRI, I. J. Desenvolvimento de projeto de sistema fotovoltaico para carga de veículos elétricos. In: SEMIC, Seminário de Iniciação Científica, 23, 2015, Curitiba-PR. Anais do 23º Seminário de Iniciação Científica. Curitiba: PUCPR, 2015. p. ELE9T.</td>
			<td width="100" align="right" rowspan=2>
				Pôster				<br>
				<img src="<?php echo base_url('img/semic/icone-poster-grad.png');?>" title="Pôster">
			</td>
		</tr>
		<tr>
			<td colspan=2 class="lt3"><font class="lt6">ELE9T</font>
				<br><b>Engenharia Elétrica</b></td>
		</tr>
		<tr>
			<td align="center"><font class="lt5"><b>Desenvolvimento de projeto de sistema fotovoltaico para carga de veículos elétricos</b></font>
			<BR>
			<font class="lt4"><i>Design of photovoltaic (pv) charging of electric vehicle (ev)</i></font>
			<BR>
			</td>
		</tr>
	</table>
	<br>
	<div style="text-align:right;">
		ANDRADE, Rodolfo de<sup>1</sup>; CHUEIRI, Ivan Jorge<sup>2</sup>		<BR>
		PIBITI		- Fundação Araucária-PIBITI		<BR>
		<I>--</I>
	</div>
	<BR>
	<table width="100%">
		<tr valign="top">
			<td width="44%"> Resumo
			<div style="text-align:justify;">
				<P>
					<B>Introdução</B>: Pensando num futuro em que possivelmente existirá um número muito maior de veículos que se utilizarão de energia elétrica ao invés da combustão para se locomover, foi desenvolvido um projeto de pesquisa para se constatar se será viável (ou não) a carga de veículos elétricos através da energia solar. O projeto foi executado em duas partes. Na primeira, uma pesquisa teórica referente a legislação de micro e mini geração de energia elétrica, sobre os produtos disponíveis no mercado nacional e o índice de irradiação solar da cidade de Curitiba. Na segunda, houve o desenvolvimento prático. Realizaram-se estudos de campo no local da instalação dos painéis elétricos, a medição da potência gerada pelas células fotovoltaicas e a carga e descarga das baterias, simulando, assim, um veículo elétrico.					<B>Objetivo</B>: A principal ideia foi a de projetar um sistema fotovoltaico para carga de veículos elétricos, com capacidade de alimentar um sistema consumidor utilizando-se de sua carga útil.					<B>Metodologia</B>: Foi empregado o uso de um relógio de sol para verificar qual seria a melhor angulação para a instalação dos painéis fotovoltaicos. Além disso, foram executadas medidas de intensidade de irradiação solar no local, para verificar se o sistema apresentaria um bom rendimento. Concluída a instalação dos painéis, iniciou-se a coleta de dados a fim de demonstrar a potência adquirida pelo sistema. A coleta de informações foi feita através de uma conexão serial entre o multímetro de bancada e o computador. Desta forma, foi possível verificar um banco de dados dispondo da corrente elétrica e da tensão fornecida entre as baterias, bem como, da corrente que consumida pela carga.					<B>Resultados</B>: No período de aquisição de dados, o sistema obteve uma corrente máxima de pico de aproximadamente 18,0285 Amperes e uma tensão máxima de pico de 36,227 Volts. Com o funcionamento de três painéis elétricos de 250 Watts em paralelo, pode-se obter uma potência máxima de aproximadamente 653,118 Watts.					<B>Conclusões</B>: A análise feita sobre planilha de dados demonstrou que, efetivamente, é viável projetar um sistema fotovoltaico para realizar a carga de veículos elétricos.				</P>
			</div><B>Palavras-chave</B>: Veículos Elétricos. Painéis Fotovoltaicos. Carga de Baterias			<BR>
			<BR>
			</td><td width="2%">&nbsp;</td><td width="44%"> Abstract
			<div style="text-align:justify;">
				<P>
					<B>Introduction</B>: Thinking about a future in which possibly there will be a much larger number of vehicles that use electricity instead of the current cars to get around, it developed a research project to determine whether they will be viable (or not) to charge electric vehicles through of solar energy. The project was executed in two parts. At first, a theoretical research related to microgeneration and minigeneration legislation of electricity, about the products available in the domestic market and the solar irradiation levels in the city of Curitiba. In the second, there was the practical development. There have been studies field at the site of installation of electrical panels, the measurement of power generated by the solar cells and the charging and discharging of batteries, simulating thus an electric vehicle.					<B>Objectives</B>: The main idea was to design a photovoltaic system for charging electric vehicles, capable of feeding a consumer system using its payload.					<B>Methods</B>: A sundial was used to determine what the best angle for the installation of photovoltaic panels. In addition, intensity of solar irradiation on site measurements were performed to verify that the system would present a good yield. Completed the installation of the panels, it began collecting data in order to demonstrate the power acquired by the system. Data collection was done through a serial connection between the bench multimeter and the computer. Thus, it was possible to check a database providing the electrical current and voltage supplied from the battery as well, the current consumed by the load.					<B>Results</B>: In the period of data acquisition, the system achieved a maximum peak current of approximately 18.02A and a maximum peak voltage of 36.22V. With the operation of three 250 Watt photovoltaic panels (PV) in parallel, we can obtain a maximum power of approximately 653.11 Watts.					<B>Conclusion</B>: The analysis on data sheet shows that, effectively, it is feasible to design a photovoltaic system to perform the charging electric vehicles.				</P>
			</div><B>Keywords</B>: Electric cars. PV. battery charge.</td>
		</tr>
	</table>
	<BR>
	<BR>
	<sup>1</sup> Estudante. PUCPR<br><sup>2</sup> Orientador. PUCPR	<BR>
	<BR>
	<BR>
	<BR>
</div>
<BR>
<BR>
<BR>
</div> 